sonar.projectKey=atjontv_kosync_0afbdd8e-9f93-4f56-821e-4ddf22b7a4b6
sonar.qualitygate.wait=true

sonar.exclusions=bearer-report.html

sonar.go.tests.reportPaths=test-report.json
sonar.go.coverage.reportPaths=coverage.out

# NOTE: Must be the same as "Version" const in internal/kosync/kosync.go
sonar.projectVersion=2026.06.1-dev.4
