### GET document progress
PUT http://localhost:8080/api/documents.update
Content-Type: application/json
x-Auth-User: meow
x-Auth-Key: 4a4be40c96ac6314e91d93f38043a634

{
  "id": "043f11771ef9d191364ac0ba08198d36",
  "owner_id": "c224572e-5bd5-4f85-a69f-981e74223cbd",
  "title": "",
  "current_location": "/body/DocFragment[1]/body/div/svg.0",
  "progress": 0.0033,
  "last_read_on_device": "Flatpak",
  "last_read_on_device_id": "BDD3C5BCA1624FE996EB00FC7948468E",
  "last_read_at": 17708364909475,
  "history": [
    {
      "id": "043f11771ef9d191364ac0ba08198d36",
      "owner_id": "c224572e-5bd5-4f85-a69f-981e74223cbd",
      "title": "",
      "current_location": "/body/DocFragment[1]/body/div/svg.0",
      "progress": 0.0033,
      "last_read_on_device": "Flatpak",
      "last_read_on_device_id": "BDD3C5BCA1624FE996EB00FC7948468E",
      "last_read_at": 17707144493656
    },
    {
      "id": "043f11771ef9d191364ac0ba08198d36",
      "owner_id": "c224572e-5bd5-4f85-a69f-981e74223cbd",
      "title": "",
      "current_location": "/body/DocFragment[1]/body/div/svg.0",
      "progress": 0.0033,
      "last_read_on_device": "Flatpak",
      "last_read_on_device_id": "BDD3C5BCA1624FE996EB00FC7948468E",
      "last_read_at": 17707144502527
    }
  ]
}
###
