//
// File:        internal/testutil/testutil.go
// Project:     https://git.obth.eu/atjontv/kosync
// Copyright:   © 2026 Thomas Obernosterer. Licensed under the EUPL-1.2 or later
//

// Package testutil builds throwaway PocketBase instances for the KOsync tests.
//
// Every app is created from an empty data directory and then migrated, so the
// tests always run against the schema that the migrations actually produce
// instead of against a committed fixture that can drift away from them.
package testutil

import (
	// KOReader hashes its passwords with MD5 before sending them, so the server
	// has to speak MD5 to talk to a device at all. The digest is never what is
	// stored: PocketBase hashes it with bcrypt on the way in.
	// bearer:disable go_gosec_blocklist_md5
	"crypto/md5" // #nosec G501 -- see above
	"fmt"
	"strings"
	"testing"
	"time"

	"git.obth.eu/atjontv/kosync/internal/schema"
	"github.com/pocketbase/pocketbase/core"
	"github.com/pocketbase/pocketbase/tests"
	"github.com/pocketbase/pocketbase/tools/filesystem"

	// Registers the KOsync collections in core.AppMigrations.
	_ "git.obth.eu/atjontv/kosync/internal/migrations"
)

// recordIdLength is the fixed width PocketBase expects from a record id.
const recordIdLength = 15

// Md5Hex returns the password digest a KOReader device would send.
func Md5Hex(password string) string {
	// bearer:disable go_gosec_crypto_weak_crypto, go_lang_weak_hash_md5
	return fmt.Sprintf("%x", md5.Sum([]byte(password))) // #nosec G401 -- see the import comment
}

// PadId turns a readable seed into a valid PocketBase record id, so that tests
// can refer to fixtures by name instead of by an autogenerated string.
func PadId(seed string) string {
	return strings.Repeat("0", recordIdLength-len(seed)) + seed
}

// NewApp returns a migrated, isolated PocketBase test instance.
func NewApp(t testing.TB) *tests.TestApp {
	t.Helper()

	app, err := tests.NewTestAppWithConfig(core.BaseAppConfig{
		DataDir:       t.TempDir(),
		EncryptionEnv: "pb_test_env",
	})
	if err != nil {
		t.Fatalf("failed to create test app: %v", err)
	}
	// tests.NewTestAppWithConfig already applies every registered migration,
	// including the KOsync ones pulled in by the blank import above.
	t.Cleanup(app.Cleanup)

	return app
}

// NewUnmigratedApp returns a bootstrapped instance whose KOsync collections do
// not exist yet, the way a fresh data directory looks before the first serve.
//
// It deliberately does not go through tests.NewTestApp, which applies every
// migration on construction.
func NewUnmigratedApp(t testing.TB) core.App {
	t.Helper()

	app := core.NewBaseApp(core.BaseAppConfig{
		DataDir:       t.TempDir(),
		EncryptionEnv: "pb_test_env",
	})

	if err := app.Bootstrap(); err != nil {
		t.Fatalf("failed to bootstrap the app: %v", err)
	}
	t.Cleanup(func() {
		_ = app.ResetBootstrapState()
	})

	return app
}

// CreateUser creates a verified WebUI account.
func CreateUser(t testing.TB, app core.App, id, email, password string) *core.Record {
	t.Helper()

	collection, err := app.FindCollectionByNameOrId(schema.CollectionUsers)
	if err != nil {
		t.Fatalf("failed to find the %q collection: %v", schema.CollectionUsers, err)
	}

	record := core.NewRecord(collection)
	if id != "" {
		record.Id = id
	}
	record.SetEmail(email)
	record.SetPassword(password)
	record.SetVerified(true)

	if err := app.Save(record); err != nil {
		t.Fatalf("failed to create user %q: %v", email, err)
	}

	return record
}

// CreateKoreaderAccount creates a device credential for the given owner.
//
// The plain password is hashed with MD5 first, exactly like the KOReader plugin
// does before it puts the digest into the "x-auth-key" header.
func CreateKoreaderAccount(t testing.TB, app core.App, owner *core.Record, id, username, password string) *core.Record {
	t.Helper()

	collection, err := app.FindCollectionByNameOrId(schema.CollectionKoreaderAccounts)
	if err != nil {
		t.Fatalf("failed to find the %q collection: %v", schema.CollectionKoreaderAccounts, err)
	}

	record := core.NewRecord(collection)
	if id != "" {
		record.Id = id
	}
	record.Set(schema.FieldUsername, username)
	record.Set(schema.FieldOwner, owner.Id)
	record.SetPassword(Md5Hex(password))

	if err := app.Save(record); err != nil {
		t.Fatalf("failed to create koreader account %q: %v", username, err)
	}

	return record
}

// CreateDocument creates a document with the given progress for the owner.
func CreateDocument(t testing.TB, app core.App, owner *core.Record, id, documentHash string, progress float64, lastReadAt time.Time) *core.Record {
	t.Helper()

	collection, err := app.FindCollectionByNameOrId(schema.CollectionDocuments)
	if err != nil {
		t.Fatalf("failed to find the %q collection: %v", schema.CollectionDocuments, err)
	}

	record := core.NewRecord(collection)
	if id != "" {
		record.Id = id
	}
	record.Set(schema.FieldOwner, owner.Id)
	record.Set(schema.FieldDocument, documentHash)
	record.Set(schema.FieldProgress, progress)
	record.Set(schema.FieldLastReadAt, lastReadAt)

	if err := app.Save(record); err != nil {
		t.Fatalf("failed to create document %q: %v", documentHash, err)
	}

	return record
}

// CreateHistoryEntry appends a superseded state to a document's history.
func CreateHistoryEntry(t testing.TB, app core.App, document *core.Record, id string, progress float64, lastReadAt time.Time) *core.Record {
	t.Helper()

	collection, err := app.FindCollectionByNameOrId(schema.CollectionDocumentHistory)
	if err != nil {
		t.Fatalf("failed to find the %q collection: %v", schema.CollectionDocumentHistory, err)
	}

	record := core.NewRecord(collection)
	if id != "" {
		record.Id = id
	}
	record.Set(schema.FieldOwner, document.GetString(schema.FieldOwner))
	record.Set(schema.FieldDocumentRef, document.Id)
	record.Set(schema.FieldProgress, progress)
	record.Set(schema.FieldLastReadAt, lastReadAt)

	if err := app.Save(record); err != nil {
		t.Fatalf("failed to create history entry for %q: %v", document.Id, err)
	}

	return record
}

// CreateBook stores a book with the two KOReader hashes set.
//
// The file is a stand-in rather than a real EPUB: the upload hook that would
// read one is a request hook, so a record saved from Go never goes near it, and
// the tests that need real books are the opt-in ones in internal/epub.
func CreateBook(t testing.TB, app core.App, owner *core.Record, id, title, hashBinary, hashFilename string) *core.Record {
	t.Helper()

	collection, err := app.FindCollectionByNameOrId(schema.CollectionBooks)
	if err != nil {
		t.Fatalf("failed to find the %q collection: %v", schema.CollectionBooks, err)
	}

	file, err := filesystem.NewFileFromBytes([]byte("PK\x03\x04 stand-in"), "book.epub")
	if err != nil {
		t.Fatalf("failed to build a stand-in file: %v", err)
	}

	record := core.NewRecord(collection)
	if id != "" {
		record.Id = id
	}
	record.Set(schema.FieldOwner, owner.Id)
	record.Set(schema.FieldFile, file)
	record.Set(schema.FieldTitle, title)
	record.Set(schema.FieldContentHash, hashBinary+hashFilename)
	record.Set(schema.FieldHashBinary, hashBinary)
	record.Set(schema.FieldHashFilename, hashFilename)

	if err := app.Save(record); err != nil {
		t.Fatalf("failed to create book %q: %v", title, err)
	}

	return record
}

// CreateBookCollection stores a hand-made shelf holding the given books.
//
// The books are stored in the order they are passed, because that order is what
// a shelf is: anything that only needs the set of books on it would be a filter
// rather than a collection.
func CreateBookCollection(t testing.TB, app core.App, owner *core.Record, id, name string, books ...*core.Record) *core.Record {
	t.Helper()

	collection, err := app.FindCollectionByNameOrId(schema.CollectionBookCollections)
	if err != nil {
		t.Fatalf("failed to find the %q collection: %v", schema.CollectionBookCollections, err)
	}

	ids := make([]string, 0, len(books))
	for _, book := range books {
		ids = append(ids, book.Id)
	}

	record := core.NewRecord(collection)
	if id != "" {
		record.Id = id
	}
	record.Set(schema.FieldOwner, owner.Id)
	record.Set(schema.FieldName, name)
	record.Set(schema.FieldBooks, ids)

	if err := app.Save(record); err != nil {
		t.Fatalf("failed to create the collection %q: %v", name, err)
	}

	return record
}

// UserToken returns a PocketBase auth token for the given user record.
func UserToken(t testing.TB, user *core.Record) string {
	t.Helper()

	token, err := user.NewAuthToken()
	if err != nil {
		t.Fatalf("failed to create an auth token: %v", err)
	}

	return token
}

// Fixture ids. They are readable on purpose so that a failing HTTP assertion
// names the record it tripped over.
var (
	IdUserA     = PadId("usera")
	IdUserB     = PadId("userb")
	IdAccountA  = PadId("accta")
	IdAccountB  = PadId("acctb")
	IdDocumentA = PadId("docva")
	IdDocumentB = PadId("docvb")
	IdHistoryA  = PadId("hista")
)

// Fixture credentials.
const (
	EmailUserA    = "alice@example.com"
	EmailUserB    = "bob@example.com"
	PasswordUsers = "a-long-enough-password"

	KoUsernameA = "alice-kobo"
	KoPasswordA = "device-secret-a"
	KoUsernameB = "bob-kindle"
	KoPasswordB = "device-secret-b"

	DocumentHashA = "043f11771ef9d191364ac0ba08198d36"
	DocumentHashB = "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d"
)

// Fixture is the seeded two-user world the API tests assert against.
type Fixture struct {
	UserA     *core.Record
	UserB     *core.Record
	AccountA  *core.Record
	AccountB  *core.Record
	DocumentA *core.Record
	DocumentB *core.Record
	HistoryA  *core.Record
}

// Seed creates two users, each with one KOReader credential and one document,
// so that every test can check that one user never sees the other's data.
func Seed(t testing.TB, app core.App) *Fixture {
	t.Helper()

	base := time.Date(2026, 3, 1, 12, 0, 0, 0, time.UTC)

	fixture := &Fixture{}
	fixture.UserA = CreateUser(t, app, IdUserA, EmailUserA, PasswordUsers)
	fixture.UserB = CreateUser(t, app, IdUserB, EmailUserB, PasswordUsers)
	fixture.AccountA = CreateKoreaderAccount(t, app, fixture.UserA, IdAccountA, KoUsernameA, KoPasswordA)
	fixture.AccountB = CreateKoreaderAccount(t, app, fixture.UserB, IdAccountB, KoUsernameB, KoPasswordB)
	fixture.DocumentA = CreateDocument(t, app, fixture.UserA, IdDocumentA, DocumentHashA, 0.25, base)
	fixture.DocumentB = CreateDocument(t, app, fixture.UserB, IdDocumentB, DocumentHashB, 0.5, base)
	fixture.HistoryA = CreateHistoryEntry(t, app, fixture.DocumentA, IdHistoryA, 0.1, base.Add(-2*time.Hour))

	return fixture
}

// SeededApp returns a migrated test app that already contains the Fixture data.
func SeededApp(t testing.TB) *tests.TestApp {
	t.Helper()

	app := NewApp(t)
	Seed(t, app)

	return app
}
