/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountSettings: typeof import('./src/components/AccountSettings.vue')['default']
    AchievementBadge: typeof import('./src/components/AchievementBadge.vue')['default']
    AchievementList: typeof import('./src/components/AchievementList.vue')['default']
    AchievementSprite: typeof import('./src/components/AchievementSprite.vue')['default']
    AuthPanel: typeof import('./src/components/AuthPanel.vue')['default']
    BookLibrary: typeof import('./src/components/BookLibrary.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DashboardMetrics: typeof import('./src/components/DashboardMetrics.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeviceList: typeof import('./src/components/DeviceList.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DocumentsList: typeof import('./src/components/DocumentsList.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    KoreaderAccounts: typeof import('./src/components/KoreaderAccounts.vue')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Menu: typeof import('primevue/menu')['default']
    MergeDialog: typeof import('./src/components/MergeDialog.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ReadStatisticsChart: typeof import('./src/components/ReadStatisticsChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SetupGuide: typeof import('./src/components/SetupGuide.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
