/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DashboardMetrics: typeof import('./src/components/DashboardMetrics.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DocumentsList: typeof import('./src/components/DocumentsList.vue')['default']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ReadStatisticsChart: typeof import('./src/components/ReadStatisticsChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
